### ISSUE TITLE
gogui dependency

### ISSUE THREAD

**Issue by kklocek** [aszady/ort#1]
Hi!

Great talk!

I saw this repo, and I have a question - where can I download "gogui" library?

**Comment by aszady** [comment]
Hi Konrad,
Thank you!

There are several "gogui" libraries, so I cannot point a particular one. Although, you may find following resources useful: 
- https://bitbucket.org/aszady/gogui (the original one)
- https://bitbucket.org/slonka/gogui (a fork)
- https://bitbucket.org/mizmuda/gogui (closest to the one I use)

Also, I'm considering publishing newer version here - in the future.

**Comment by kklocek** [comment]
@aszady : Ok, it would be so good to point it in documentation for newbie user.

Closing this issue.

**Comment by aszady** [comment]
The documentation is being created. It will be delivered before Dec 4, 2016 11.00AM CET.
